name: E2E Test On PR

on:
  workflow_run:
    workflows: ["Bump versions"]
    types:
      - completed
  push:
  pull_request:
   types: [opened, synchronize, reopened, closed]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    env:
      CI: true
      NODE_ENV: test
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
    steps:
      - name: Log node version
        run: node --version

      - uses: actions/checkout@v2
        with:
         fetch-depth: '0'
      
      - name: Install dependencies
        run: yarn install

      - name: Lint
        run: yarn lint

      - name: Run tsc
        run: yarn tsc
      
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          start: yarn dev
          wait-on: 'http://localhost:3000'
          project: ./packages/app
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  package-update:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Update npm packages
      uses: technote-space/create-pr-action@v2
      with:
         EXECUTE_COMMANDS: |
           npx npm-check-updates -u --packageFile package.json
           yarn install
           yarn backstage-cli versions:bump
           yarn upgrade
         COMMIT_MESSAGE: 'chore: update npm dependencies'
         COMMIT_NAME: 'GitHub Actions'
         COMMIT_EMAIL: 'bot@roadie.io'
         PR_BRANCH_NAME: 'chore-npm-update-${PR_ID}'
         PR_TITLE: 'chore: update npm dependencies'